name: Build Train To Atlassa

on:
  workflow_dispatch:

jobs:
  release-build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build release distributions
        run: pyinstaller --onefile main.py --name=TrainToAtlassa

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: build-windows
          path: dist/
